# -*- coding: utf-8 -*-
"""Phase 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QdZwSQb4j1HUr0kKgBPAKnvdhDPEKshn
"""

import pandas as pd
import numpy as np


# قراءة الداتا
def load_data(path):
    df = pd.read_csv("/content/AmesHousing.csv")
    return df


# استكشاف البيانات
def explore_data(df):
    print("Column Names:")
    print(df.columns)

    print("\nShape:", df.shape)

    print("\nInfo:")
    df.info()


# القيم المفقودة
def check_missing(df):
    missing = df.isnull().sum().sort_values(ascending=False)

    print("\nMissing values per column:")
    print(missing)

    return missing


# التكرارات
def check_duplicates(df):
    duplicates = df.duplicated().sum()
    print("\nDuplicates:", duplicates)
    return duplicates


# حذف الأعمدة التي فيها missing
def drop_high_missing(df):
    df = df.drop(columns=df.columns[df.isna().mean() > 0.5])
    return df


# تعويض القيم المفقودة
def fill_missing(df):

    # الأعمدة الرقمية
    num_cols = df.select_dtypes(include=np.number).columns
    df[num_cols] = df[num_cols].fillna(df[num_cols].median())

    # الأعمدة النصية
    cat_cols = df.select_dtypes(include="object").columns
    df[cat_cols] = df[cat_cols].fillna("Unknown")

    return df


# حذف التكرارات
def remove_duplicates(df):
    df = df.drop_duplicates()
    return df


# التحقق النهائي
def final_checks(df):

    print("\nNo missing values:", df.isnull().sum().sum())

    if "SalePrice" in df.columns:
        print("All SalePrice > 0:", (df["SalePrice"] > 0).all())

    print("Final shape:", df.shape)



# استدعاءات

df = load_data("AmesHousing.csv")

explore_data(df)

check_missing(df)

check_duplicates(df)

df = drop_high_missing(df)

df = fill_missing(df)

df = remove_duplicates(df)

final_checks(df)